fix: Adding the cdk synth and cdk bootstrap steps

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -84,5 +84,16 @@ jobs:
         run: npm install
       - name: Install AWS CDK CLI
         run: npm install -g aws-cdk
+      - name: CDK Synth
+        run: cdk synth
+      - name: CDK Bootstrap
+        run: |
+          AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}
+          if [ -z "$AWS_ACCOUNT_ID" ]; then
+            echo "Missing AWS_ACCOUNT_ID variable in the selected GitHub environment."
+            exit 1
+          fi
+          AWS_REGION=${{ inputs.aws-region || github.event.inputs.aws-region || 'ap-southeast-2' }}
+          cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
       - name: CDK Deploy
         run: cdk deploy --all --require-approval never
